apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: cluster-banner
spec:
  text: {{ .Values.console.banner.text }}
  location: BannerTop
  color: '#FFFFFF'
  backgroundColor: 'FF0000'
